// Generated by ts-to-zod
import { z } from "zod";
import { WebSocketOutgoingMessageType } from "./request-types";

export const webSocketOutgoingMessageTypeSchema = z.nativeEnum(
  WebSocketOutgoingMessageType
);

export const webSocketOutgoingVoteChangedMessageSchema = z.object({
  type: z.literal(WebSocketOutgoingMessageType.VoteChanged),
  payload: z.object({}),
});

export const webSocketOutgoingMessageSchema =
  webSocketOutgoingVoteChangedMessageSchema;
